name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t alebrixel/frontend-wsl -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true alebrixel/frontend-wsl npm test
 
      - run: docker build -t alebrixel/multi-client-10-14 ./client
      - run: docker build -t alebrixel/multi-nginx-10-14 ./nginx
      - run: docker build -t alebrixel/multi-server-10-14 ./server
      - run: docker build -t alebrixel/multi-worker-10-14 ./worker
 
      - run: docker push alebrixel/multi-client-10-14
      - run: docker push alebrixel/multi-nginx-10-14
      - run: docker push alebrixel/multi-server-10-14
      - run: docker push alebrixel/multi-worker-10-14
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: frontend-docker
          environment_name: Frontend-docker-env
          existing_bucket_name: elasticbeanstalk:eu-north-1:104167272345
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip